./ej2 tests_tiempos/mejor_caso/mejor_caso_3_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_3_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_4_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_4_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_5_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_5_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_6_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_6_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_7_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_7_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_8_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_8_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_9_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_9_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_10_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_10_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_11_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_11_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_50_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_50_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_100_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_100_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_150_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_150_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_200_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_200_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_250_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_250_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_300_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_300_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_350_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_350_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_400_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_400_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_450_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_450_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_500_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_500_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_550_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_550_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_600_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_600_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_650_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_650_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_700_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_700_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_750_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_750_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_800_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_800_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_850_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_850_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_900_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_900_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_950_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_950_vertices &&
./ej2 tests_tiempos/mejor_caso/mejor_caso_1000_vertices.in hare tests_tiempos/resultados_mejor_caso_sin_2lc/res_1000_vertices 
exit
